/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheHaircareChallengeRouteImport } from './routes/the-haircare-challenge'
import { Route as R14TheHaircareChallengeRouteImport } from './routes/14-the-haircare-challenge'
import { Route as IndexRouteImport } from './routes/index'

const TheHaircareChallengeRoute = TheHaircareChallengeRouteImport.update({
  id: '/the-haircare-challenge',
  path: '/the-haircare-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const R14TheHaircareChallengeRoute = R14TheHaircareChallengeRouteImport.update({
  id: '/14-the-haircare-challenge',
  path: '/14-the-haircare-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/14-the-haircare-challenge': typeof R14TheHaircareChallengeRoute
  '/the-haircare-challenge': typeof TheHaircareChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/14-the-haircare-challenge': typeof R14TheHaircareChallengeRoute
  '/the-haircare-challenge': typeof TheHaircareChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/14-the-haircare-challenge': typeof R14TheHaircareChallengeRoute
  '/the-haircare-challenge': typeof TheHaircareChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/14-the-haircare-challenge' | '/the-haircare-challenge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/14-the-haircare-challenge' | '/the-haircare-challenge'
  id:
    | '__root__'
    | '/'
    | '/14-the-haircare-challenge'
    | '/the-haircare-challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R14TheHaircareChallengeRoute: typeof R14TheHaircareChallengeRoute
  TheHaircareChallengeRoute: typeof TheHaircareChallengeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-haircare-challenge': {
      id: '/the-haircare-challenge'
      path: '/the-haircare-challenge'
      fullPath: '/the-haircare-challenge'
      preLoaderRoute: typeof TheHaircareChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/14-the-haircare-challenge': {
      id: '/14-the-haircare-challenge'
      path: '/14-the-haircare-challenge'
      fullPath: '/14-the-haircare-challenge'
      preLoaderRoute: typeof R14TheHaircareChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R14TheHaircareChallengeRoute: R14TheHaircareChallengeRoute,
  TheHaircareChallengeRoute: TheHaircareChallengeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
